#!/usr/bin/env bash

# If any command fails, exit immediately with that command's exit status
set -eo pipefail

NORMALCOLOR="\\033[0;39m"
GREENCOLOR="\\033[1;32m"
REDCOLOR="\\033[1;31m"
echoGREEN() {
  echo -e "$GREENCOLOR" "$1" "$NORMALCOLOR"
}

echoRED() {
  echo -e "$REDCOLOR" "$1" "$NORMALCOLOR"
}

# prevent committing to main branch
branch="$(git rev-parse --abbrev-ref HEAD)"
forbiddenBranch="main"

if [ "$branch" = "$forbiddenBranch" ]; then
  echoRED "You can't commit directly to the $forbiddenBranch branch"
  exit 1
fi

# run my-notes checks
if [ -f "my-notes/githooks/pre-commit" ]; then
    echo "run my-notes/githooks/pre-commit"
    my-notes/githooks/pre-commit
fi

CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
ROOT_FOLDER=$(git rev-parse --show-toplevel)

# run pc-web-components checks
if [[ $CHANGED_FILES == *"pc-web-components/"* ]]
then
    echo "run pc-web-components eslint"
    cd $ROOT_FOLDER/pc-web-components
    yarn lint
    echoGREEN "run pc-web-components eslint passed"
fi
