# https://aws.amazon.com/blogs/devops/integrating-with-github-actions-ci-cd-pipeline-to-deploy-a-web-app-to-amazon-ec2/

# TODO:
# TODO:
# TODO:
name: My notes ui deploy

on:
  workflow_dispatch: {}

env:
  applicationfolder: my-notes-ui
  WORKING_DIRECTORY: my-notes-ui/my-notes/packages/pc-web
  AWS_REGION: eu-west-2
  S3BUCKET: ##s3-bucket## 

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - uses: ./.github/actions/use-node
        with:
          yarn-lock-path: my-notes/yarn.lock

      - name: chmod
        run: chmod -R +x ./.github

      - uses: ./.github/actions/install-packages
        with:
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Yarn build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build
      - name: Package
        id: package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build

      - name: Zip build directory
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.zip s3://${{ env.S3BUCKET }}/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name CodeDeployAppNameWithASG --deployment-group-name CodeDeployGroupName --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures
